"""
ATS Integration endpoint (single call)
======================================
ONE call the ATS makes to start an interview for a candidate. The ATS sends only
IDs; we pull the candidate's resume/score/job from the ATS db, trigger the
interview, and return the join_url + trigger data.

    ATS ──►  POST /api/v1/integration/interview     X-API-Key: <connector key>
             { candidate_id, job_id, tenant_id }
                 │
             ats_connector.fetch_trigger_payload()   (reads ATS db, read-only)
                 │
             build_interview_context()               (strategy, room, invite, email)
                 │
             ◄──  { interview_id, join_url, status, evaluation_weights }

Auth: the Connector API key (X-API-Key). Exempt from TenantMiddleware — the
tenant is supplied in the body.
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.api_key import verify_connector_api_key
from app.db.session import get_db
from app.services import ats_connector
from app.services.context_builder import build_interview_context

router = APIRouter()


class IntegrationInterviewRequest(BaseModel):
    """What the ATS sends — just the two identifiers. We pull the rest from their
    db and derive the tenant from ORG_ID ourselves."""
    candidate_id: str
    job_id: str


class IntegrationInterviewResponse(BaseModel):
    interview_id: str
    ats_candidate_id: str            # echoes the candidate_id you sent (e.g. "420")
    tenant_id: str                   # generated by us from the ATS ORG_ID (e.g. "org-1266")
    status: str
    join_url: str
    message: str
    evaluation_weights: dict[str, Any] | None = None


@router.post(
    "/integration/interview",
    response_model=IntegrationInterviewResponse,
    dependencies=[Depends(verify_connector_api_key)],
)
async def integration_interview(
    body: IntegrationInterviewRequest,
    db: AsyncSession = Depends(get_db),
):
    # 1. Pull candidate + resume + score + job from the ATS db → trigger body.
    #    Also derives tenant_id from the ATS ORG_ID (same org → same tenant).
    #    ATSDataError carries a precise status (404/422/502/503) so the ATS team
    #    can debug their integration.
    try:
        payload, tenant_id = await ats_connector.fetch_trigger_payload(
            candidate_id=body.candidate_id,
            job_id=body.job_id,
        )
    except ats_connector.ATSDataError as e:
        raise HTTPException(status_code=e.status_code, detail=e.detail)

    # 2. Reuse the existing orchestrator: strategy, room, invite token, email.
    try:
        result = await build_interview_context(
            request=payload,
            tenant_id=tenant_id,
            db=db,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    return IntegrationInterviewResponse(
        interview_id=result["interview_id"],
        ats_candidate_id=body.candidate_id,   # echo the id you sent
        tenant_id=tenant_id,                  # generated from ORG_ID
        status="scheduled",
        join_url=result["join_url"],
        message=f"Interview scheduled for {result['candidate_name']}.",
        evaluation_weights=result.get("evaluation_weights"),
    )
