from datetime import datetime

from sqlalchemy import String, Integer, BigInteger, Boolean, Text, DateTime, Numeric
from sqlalchemy.dialects.postgresql import JSONB, ARRAY
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import BaseModel


class Interview(BaseModel):
    """Main interview record — created when ATS triggers L1."""
    __tablename__ = "interviews"

    candidate_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    job_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    # scheduled, in_progress, completed, failed, no_show
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="scheduled")

    # browser (Phase 1), phone (Phase 2)
    mode: Mapped[str] = mapped_column(String(20), nullable=False, default="browser")

    join_url: Mapped[str] = mapped_column(String(500), nullable=True)
    join_expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)

    scheduled_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    ended_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    duration_seconds: Mapped[int] = mapped_column(Integer, nullable=True)

    recording_s3_key: Mapped[str] = mapped_column(String(500), nullable=True)
    transcript_s3_key: Mapped[str] = mapped_column(String(500), nullable=True)


class InterviewContext(BaseModel):
    """AI-generated interview strategy built from resume + ATS score + JD."""
    __tablename__ = "interview_contexts"

    interview_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    # What to verify from resume claims
    skills_to_validate: Mapped[list] = mapped_column(ARRAY(Text), nullable=True)

    # Gaps from ATS score — AI will ask about these
    gaps_to_probe: Mapped[list] = mapped_column(ARRAY(Text), nullable=True)

    # Projects on resume — AI will ask candidate to explain
    projects_to_ask: Mapped[list] = mapped_column(ARRAY(Text), nullable=True)

    # Specific experience claims to verify
    experience_to_verify: Mapped[dict] = mapped_column(JSONB, nullable=True)

    # LLM-generated plain text strategy summary
    interview_strategy: Mapped[str] = mapped_column(Text, nullable=True)

    # Full question flow for this interview (loaded into LangGraph)
    question_flow: Mapped[dict] = mapped_column(JSONB, nullable=True)


class InterviewTranscript(BaseModel):
    """Every single message exchanged during the interview."""
    __tablename__ = "interview_transcripts"

    interview_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    # ai or candidate
    speaker: Mapped[str] = mapped_column(String(20), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    spoken_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)

    # Which question node this message belongs to (intro, salary, etc.)
    interview_node: Mapped[str] = mapped_column(String(50), nullable=True)


class InterviewExtractedData(BaseModel):
    """Structured data extracted from the conversation by the evaluation engine."""
    __tablename__ = "interview_extracted_data"

    interview_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    current_company: Mapped[str] = mapped_column(String(255), nullable=True)
    current_role: Mapped[str] = mapped_column(String(255), nullable=True)
    total_experience_years: Mapped[float] = mapped_column(Numeric(4, 1), nullable=True)

    current_ctc: Mapped[int] = mapped_column(BigInteger, nullable=True)
    expected_ctc: Mapped[int] = mapped_column(BigInteger, nullable=True)

    notice_period_days: Mapped[int] = mapped_column(Integer, nullable=True)
    notice_negotiable: Mapped[bool] = mapped_column(Boolean, nullable=True)

    relocation_willing: Mapped[bool] = mapped_column(Boolean, nullable=True)
    preferred_locations: Mapped[list] = mapped_column(ARRAY(Text), nullable=True)

    shift_flexible: Mapped[bool] = mapped_column(Boolean, nullable=True)
    work_authorization: Mapped[str] = mapped_column(String(100), nullable=True)
    earliest_joining: Mapped[str] = mapped_column(String(50), nullable=True)

    # Full raw extraction output from LLM
    raw_extraction: Mapped[dict] = mapped_column(JSONB, nullable=True)


class InterviewScore(BaseModel):
    """Final evaluation scores generated by Claude Sonnet after the interview."""
    __tablename__ = "interview_scores"

    interview_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    communication_score: Mapped[int] = mapped_column(Integer, nullable=True)  # 1-10
    confidence_score: Mapped[int] = mapped_column(Integer, nullable=True)     # 1-10
    jd_fit_score: Mapped[int] = mapped_column(Integer, nullable=True)         # 1-10
    behavioral_score: Mapped[int] = mapped_column(Integer, nullable=True)     # 1-10

    salary_fit: Mapped[bool] = mapped_column(Boolean, nullable=True)
    experience_validated: Mapped[bool] = mapped_column(Boolean, nullable=True)

    overall_score: Mapped[int] = mapped_column(Integer, nullable=True)        # 0-100

    # proceed_to_l2, reject, hold
    recommendation: Mapped[str] = mapped_column(String(20), nullable=True)

    # LLM reasoning — shown to recruiter as summary
    ai_reasoning: Mapped[str] = mapped_column(Text, nullable=True)

    # Recruiter can override the AI recommendation
    recruiter_override: Mapped[str] = mapped_column(String(20), nullable=True)
    override_reason: Mapped[str] = mapped_column(Text, nullable=True)
    override_by: Mapped[str] = mapped_column(String(36), nullable=True)
    override_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
